[toolchain]
channel = "stable"
components = [ "rustfmt"]
targets = [ "x86_64-unknown-linux-gnu", "aarch64-linux-android", "armv7-linux-androideabi", "i686-linux-android", "x86_64-linux-android" ]
profile = "minimal"
